pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/TurboMiki/devops-mini-lab.git'
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform') {
                    sh '''
                        curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
                        unzip -o terraform.zip
                        chmod +x terraform
                        ./terraform version
                        ./terraform init
                        ./terraform validate
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh '''
                        ./terraform apply
                    '''
                }
            }
        }

        stage('Done') {
            steps {
                echo 'All done!'
            }
        }
    }
}
