pipeline {
    agent any

    environment {
        TERRAFORM_VERSION = "1.8.4"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/TurboMiki/devops-mini-lab.git'
            }
        }

        stage('Install Terraform') {
            steps {
                dir('terraform') {
                    sh '''
                        curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
                        unzip -o terraform.zip
                        chmod +x terraform
                        export PATH=$PWD:$PATH
                    '''
                }
            }
        }

        stage('Terraform Init & Validate') {
            steps {
                dir('terraform') {
                    sh '''
                        export PATH=$PWD:$PATH
                        terraform init
                        terraform validate
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh '''
                        export PATH=$PWD:$PATH
                        terraform plan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh '''
                        export PATH=$PWD:$PATH
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Done') {
            steps {
                echo 'All done!'
            }
        }
    }
}
